[tool.poetry.scripts]
flow = 'gtnhvelo.cli:main'

[tool.poetry]
name = "gtnhvelo"
version = "0.1.2"
description = "Factory Optimization Flowcharts for Gregtech: New Horizons"
authors = ["velolib <vlocitize@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
graphviz = "^0.20.1"
PyYAML = "^6.0"
rich = "^13.0.0"
sympy = "^1.11.1"
typer = "^0.7.0"
prompt-toolkit = "^3.0.36"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
autopep8 = "^2.0.1"
pre-commit = "^2.21.0"
mypy = "^0.991"
types-pillow = "^9.4.0.0"
types-pyyaml = "^6.0.12.2"
types-pygments = "^2.14.0.0"
types-colorama = "^0.4.15.4"
types-commonmark = "^0.9.2"

[tool.autopep8]
ignore = "E402"
max_line_length = 120
recursive = true
in-place = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
