[project]
name = 'gtnhvelo'
description = 'Factory Optimization Flowcharts for Gregtech: New Horizons'
requires-python = '>=3.10'
readme = 'README.md'
version = '0.1.2'
authors = [
    { name = 'velo', email = 'vlocitize@gmail.com' }
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',

]
dependencies = [
    'attrs>=22.1.0',
    'certifi>=2022.12.7',
    'charset-normalizer>=2.1.1',
    'click>=8.1.3',
    'colorama>=0.4.6',
    'commonmark>=0.9.1',
    'docutils>=0.19',
    'exceptiongroup>=1.0.4',
    'flit>=3.8.0',
    'flit_core>=3.8.0',
    'graphviz>=0.20.1',
    'idna>=3.4',
    'iniconfig>=1.1.1',
    'mpmath>=1.2.1',
    'packaging>=21.3',
    'pipdeptree>=2.3.3',
    'pluggy>=1.0.0',
    'Pygments>=2.14.0',
    'pyparsing>=3.0.9',
    'pyreadline3>=3.4.1',
    'pytest>=7.2.0',
    'PyYAML>=6.0',
    'requests>=2.28.1',
    'rich>=13.0.0',
    'sympy>=1.11.1',
    'tomli>=2.0.1',
    'tomli_w>=1.0.0',
    'typer>=0.7.0',
    'urllib3>=1.26.13',
]

[build-system]
build-backend = 'flit_core.buildapi'
requires = ['flit_core >=3.2,<4']

[project.scripts]
flow = 'gtnhvelo.cli:main'

[project.optional-dependencies]
tests = [
    'pytest>=7.2.0',
]