# yaml-language-server: $schema=https://raw.githubusercontent.com/velolib/gregtech-flow/master/src/gregtech/flow/resources/config_schema.json
# VSCode Users use this extension: https://github.com/redhat-developer/vscode-yaml

# GT: Flow CONFIGURATION FILE
# DELETE THIS FILE TO REGENERATE UPON RUNNING
# Documentation: https://velolib.github.io/gregtech-flow/docs/documentation/configuration.html
CONFIG_VER: 2

GRAPHVIZ: path
# Input your graphviz /Graphivz/bin directory path in quotes
# Type 'path' if you want to use the PATH environment variable

# === FUNCTIONALITY SETTINGS ===
POWER_LINE: true # Automatically burns all leftover fuels
DO_NOT_BURN: # If POWER_LINE is true, don't burn these
  - hydrogen
  - coal tar oil
  - phenol
  - naphtha
  - biomass
  - oil
  - steam
  - creosote oil
OUTPUT_FORMAT: svg # png or pdf (pdf is searchable)
USE_RAINBOW_EDGES: true # feature to help distinguish between overlapping edges
DUR_FORMAT: sec # choose either "ticks" or "sec"
VIEW_ON_COMPLETION: true

PRINT_BOTTLENECKS: false
USE_BOTTLENECK_EXACT_VOLTAGE: false
BOTTLENECK_MIN_VOLTAGE: iv
MAX_BOTTLENECKS: 5

# === VISUALS ===
## === FONTS ===
GENERAL_FONT: arial # nodes and edges
SUMMARY_FONT: arial
GROUP_FONT: verdana
TITLE_FONT: verdana

NODE_FONTSIZE: 14
EDGE_FONTSIZE: 13
GROUP_FONTSIZE: 20
TITLE_FONTSIZE: 40

## === COLORS ===
BACKGROUND_COLOR: '#140e52'
TITLE_COLOR: '#ffffff'
SUMMARY_COLOR: '#ffffff'
EDGECOLOR_CYCLE:
  # Legacy colors
  # - '#b58900' # 'yellow'
  # - '#cb4b16' # 'orange'
  # - '#dc322f' # 'red'
  # - '#d33682' # 'magenta'
  # - '#6c71c4' # 'violet'
  # - '#268bd2' # 'blue'
  # - '#2aa198' # 'cyan'
  # - '#859900' # 'green'
  - '#ff6961'
  - '#ffb480'
  - '#f8f38d'
  - '#42d6a4'
  - '#08cad1'
  - '#59adf6'
  - '#9d94ff'
  - '#c780e8'
SOURCESINK_COLOR: white
NONLOCKEDNODE_COLOR: lightcyan
LOCKEDNODE_COLOR: chartreuse
POSITIVE_COLOR: chartreuse
NEGATIVE_COLOR: crimson

## === EXTRA ===
POWER_UNITS: eut
# Only affects nodes
# eut: Use absolute eu/t numbers, example: 32 EU/t
# auto: Use user-defined power tier
# lv, mv, hv, ev, etc.: Use amps

ORIENTATION: TB
# TB: Vertical, LR: Horizontal, BT: Vertical Inverted, RL: Horizontal Inverted
# [TB, LR, BT, RL]

LINE_STYLE: spline
# [line, spline, polyline, curved]

RANKSEP: 1.5
NODESEP: 0.5
# Node separation size in X/Y.
# This is a suggestion, the graphing algorithm will ignore numbers that are too small.

COMBINE_INPUTS: true
COMBINE_OUTPUTS: true
# Whether to (visually) create a new meta node before multi-input/after multi-output ports

# { You should probably only modify these if you are dev
DEBUG_LOGGING: false
DEBUG_SHOW_EVERY_STEP: false
SHOW_MACHINE_INDICES: false
STRIP_BRACKETS: true
# }
